### ISSUE TITLE
Should I use tutime.cn or zzzhi.com as Tutu's website?

### ISSUE THREAD

**Issue by Lafcadia** [Lafcadia/Lafcadia#1]
@zzhiro

**Comment by cheezhi** [comment]
> @zzhiro

zzzzhi.com is still unfinished. You can choose not to update the friend link information until I notify you to update it,  or update it with new information now (you can view the new information at https://www.zzzzhi.com/#/friends).

**Comment by Lafcadia** [comment]
Surely, thanks!
